#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Background
feh --bg-scale $HOME/Pictures/wallpaper/winterreise.jpg &

# Polybar
sh $HOME/.config/polybar/launch.sh 6

bspc monitor -d I II III IV V

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#c8b895"

# Application
bspc rule -a Gimp        desktop='^8' state=floating follow=on
bspc rule -a Firefox     desktop='^2'
bspc rule -a libreoffice desktop='^5'

# Utilities
bspc rule -a spectacle state=floating
bspc rule -a eog       state=floating
